services:
  postgres:
    image: docker.io/postgres:12
    ports:
      -  "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - orchestr8
networks:
  orchestr8:
    name: orchestr8
    external: true