services:
  redis:
    image: docker.io/redis:6
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      - REDIS_AOF_ENABLED=false
    networks:
      - orchestr8
  postgres:
    image: docker.io/postgres:12
    ports:
      -  "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - orchestr8
networks:
  orchestr8:
    name: orchestr8
    external: true